version: '3.9'
services:
  pgadmin4:
    restart: always
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=hssong1024@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - 5050:80
    depends_on:
      - postgre-db

  postgre-db:
    restart: always
    build: ./postgre-db
    volumes:
      - ./postgre-db/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432