version: '3.9'

services:
  actix-web-server:
    restart: always
    build: ./server
    ports:
      - 8080:8080
    depends_on:
      - postgre-db

  postgre-db:
    restart: always
    build: ./postgre-db
    volumes:
      - ./postgre-db/pgdata:/var/lib/postgresql/data/pgdata

  # 필요시 주석제거후 생성
  # pgadmin4:
  #   restart: always
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=hssong1024@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=pgadmin
  #   ports:
  #     - 5050:80
  #   depends_on:
  #     - postgre-db