[package]
name = "myerror"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
env_logger = "0"
derive_more = "0.99.17"
serde = "1"
serde_json = "1.0"